Fix TestWriteDefaultConfig with -count 2
I forgot to clear the environment, which means that the test may fail if
the dev's environment isn't what we expect. Even worse, it makes
subsequent runs of the same test fail:

	$ go test -run TestWriteDefaultConf -count 2
	--- FAIL: TestWriteDefaultConf (0.00s)
		config_test.go:12: Expected ListenPort to be set to its default