[TT-7316] Use python 3.9 in CI tests (#4503)
<!-- Provide a general summary of your changes in the Title above -->

## Description

```
Run actions/setup-python@v2
  with:
    python-version: [3](https://github.com/TykTechnologies/tyk/actions/runs/3646579334/jobs/6157812544#step:6:3).5
    token: ***
  env:
    TYK_DB_REDISHOST: localhost
    TYK_GW_STORAGE_HOST: localhost
    GOROOT: /opt/hostedtoolcache/go/1.16.15/x6[4](https://github.com/TykTechnologies/tyk/actions/runs/3646579334/jobs/6157812544#step:6:4)
Version 3.[5](https://github.com/TykTechnologies/tyk/actions/runs/3646579334/jobs/6157812544#step:6:5) was not found in the local cache
Error: Version 3.5 with arch x[6](https://github.com/TykTechnologies/tyk/actions/runs/3646579334/jobs/6157812544#step:6:6)4 not found
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```

There are particular 3.5 versions in the manifest, trying to pin 3.5.10
in particular.

Upstream issue tells that we need to update to 3.7 (3.6 was end-of-life
in december 2021)
<!-- Describe your changes in detail -->

## Related Issue

<!-- This project only accepts pull requests related to open issues. -->
<!-- If suggesting a new feature or change, please discuss it in an
issue first. -->
<!-- If fixing a bug, there should be an issue describing it with steps
to reproduce. -->
<!-- OSS: Please link to the issue here. Tyk: please create/link the
JIRA ticket. -->
Blocking CI on multiple PRs.

https://tyktech.atlassian.net/browse/TT-7316

## Motivation and Context

<!-- Why is this change required? What problem does it solve? -->
Unblock PRs.

## How This Has Been Tested

CI checks below.

<!-- Please describe in detail how you tested your changes -->
<!-- Include details of your testing environment, and the tests -->
<!-- you ran to see how your change affects other areas of the code,
etc. -->
<!-- This information is helpful for reviewers and QA. -->

## Screenshots (if appropriate)

## Types of changes

<!-- What types of changes does your code introduce? Put an `x` in all
the boxes that apply: -->

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test
coverage to functionality)

## Checklist

<!-- Go over all the following points, and put an `x` in all the boxes
that apply -->
<!-- If there are no documentation updates required, mark the item as
checked. -->
<!-- Raise up any additional concerns not covered by the checklist. -->

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning
why it's required
- [ ] I would like a code coverage CI quality gate exception and have
explained why

Co-authored-by: Tit Petric <tit@tyk.io>